### PR TITLE
Try old source while waiting for a proper release of new fork

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins trying this out just to see if it works. This is what is being used by QGIS, and according to the maintainer there are no plans to start using the new source, since, in his own words " next stop is Qt6 and that means no more webkit".

I am trying to know more about the qt6 migration plans. I know there were a few meetings about it already.

**Comment by gillins** [comment]
```
$SRC_DIR/build/DerivedSources/WebCore/CSSGrammar.cpp:160:10: fatal error: CSSGrammar.hpp: No such file or directory
```

**Comment by gillins** [comment]
Windows ok though, we must be missing a step.

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@SrNetoChan do you know if QGIS does anything special here to build for OSX? I'm stuck, must be some fix that came in after this that was in the snapshot I was using...

**Comment by SrNetoChan** [comment]
No idea. I will try to find the recipe used by the original osx builds.

Meanwhile, I compared your source from google drive and the source we are using here. I can't make much out of it, but here's a patch between the two folders:

https://drive.google.com/file/d/1wmKpjsVs1R44KDMHiVuMAjxCVMqxBgiC/view?usp=sharing

**Comment by gillins** [comment]
Thanks @SrNetoChan, I'll see if I can just apply that whole patch and see what happens - in theory the new builds will be 100% compatible with the old....

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Or just use your source. I got some extra information. QGIS developers are already working on qt6 builds. The project is going to fund some work. It seems that at some point the project will maintain qt5 and qt6 builds side by side, and latwr they will drop qt5 (and webkit).

**Comment by gillins** [comment]
Thanks @SrNetoChan, so `qt6` builds won't need `qtwebkit`? Sounds like we won't need to maintain this mess for much longer which is good.

**Comment by SrNetoChan** [comment]
> Thanks @SrNetoChan, so `qt6` builds won't need `qtwebkit`? Sounds like we won't need to maintain this mess for much longer which is good. 

There's no webkit in qt6. There are a bunch of limitations and stuff that qtwebengine (what replaces qtwebkit) does not allow to do yet, that affects some of QGIS functionality. That's why developers are giving baby steps on this. Meanwhile, we should stick with this source, QGIS has no plans trying to use the maintained qtwebkit repository.

**Pull request merged**
