### PR TITLE
Go back to qt-main again with higher version on qt

### PR DESCRIPTION
**Pull request by SrNetoChan**
Move qt dependency to 5.15 so that we can migrate pyqtwebkit and them qgis to newest versions

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@izahn @gillins my plan was to bump qtwebkit to qt 5.15, then pyqtwebkit, then QGIS.

I plan to start by a lower version of QGIS 3.22 (which is the LTR) and once is building, merge it into the LTR branch and go for 3.24.

**Comment by izahn** [comment]
I'm all for this, but note that it will make things incompatible with all the other packages that still depend on `qt=5.12`. We need to migrate everything, as is being discussed in https://github.com/conda-forge/qt-feedstock/pull/227#issuecomment-1119917414

**Comment by SrNetoChan** [comment]
> I'm all for this, but note that it will make things incompatible with all the other packages that still depend on `qt=5.12`. We need to migrate everything, as is being discussed in [conda-forge/qt-feedstock#227 (comment)](https://github.com/conda-forge/qt-feedstock/pull/227#issuecomment-1119917414)

Hi @izahn _If I understand correctly this might make QGIS versions incompatible with other packages, right? Or are we worried about other packages being affected by this bump of webkit?

Since there aren't any plans for mass migration, I just wanted to put QGIS moving into earlier versions, especially the latest LTR 3.22, maybe we will need more work to make it compatible with for example qtconsole and others useful packages to work together with qgis. Since QGIS will have brand new versions, anyone wanting to keep compatibility can still keep using 3.16 or 3.18, no?

I think there are other dependencies that need to be bumped as well just to build QGIS, like qtlocation for example.

Are you aware of what other packages, nor related to QGIS need migrating to qt5.15?

**Comment by izahn** [comment]
There *are* plans for a mass migration, just that those plans may take time to come to fruition. Everything is ready, basically someone just needs to write a migrator as discussed inhttps://github.com/conda-forge/qt-feedstock/pull/227#issuecomment-1119917414. Unfortunately I don't know how to do that and haven't had time to learn.

The basic issue is that packages built with `qt=5.12` will not be compatible with packages built with `qt-main=5.15`. There are a lot of packages involved:

```
 ~/D/rcs__cluster_software_modules $ mamba repoquery whoneeds qt -c conda-forge -q | cut -d" " -f 2  | uniq

the

Name
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
appimage-updater-bridge
attica
codes-ui
colmap
daetools
ecflow
extra-cmake-modules
fcitx-qt5
freecad
gammaray
gazebo
geant4
geant4-base
gepetto-viewer
gepetto-viewer-corba
ggplot
gimagereader-qt
gnuplot
gnuradio
gnuradio-qtgui
gqrx
hpp-gepetto-viewer
hpp-gui
hyperspy
ipe
jasp
jkqtplotter
karchive
kauth
kbookmarks
kcodecs
kcompletion
kconfig
kconfigwidgets
kcoreaddons
kcrash
kdbusaddons
kdeclarative
kdenlive
kfilemetadata
kglobalaccel
kguiaddons
ki18n
kiconthemes
kio
kirigami2
kitemmodels
kitemviews
kjobwidgets
knewstuff
knotifications
knotifyconfig
kpackage
kservice
ktextwidgets
kwallet
kwidgetsaddons
kwindowsystem
kxmlgui
libignition-gazebo4
libignition-gazebo5
libignition-gazebo6
libignition-gui4
libignition-gui5
libignition-gui6
libignition-launch3
libignition-launch4
libignition-launch5
libopencv
libqglviewer
lxqt-build-tools
lyx
magics
magics-metview
metview
mss
nionui-tool
octave
opencv
openscenegraph-osgqt
ovito
paraview
pcraster
phonon
pivy
poppler-qt
prismatic_gui
puma
purpose
pyprismatic
pyqt
pyqt-impl
pyqtads
pyqtchart
pyqtwebengine
pyqtwebkit
pyside
pyside2
qca
qgis
qjson
qscintilla2
qtkeychain
qtlocation
qtserialport
qtspell
qtwebkit
quazip
qwt
qwtpolar
root
root-binaries
root-dependencies
simage
solid
sonnet
soqt
texmaker
tomviz
veusz
vtk
xray-vision
zeit
ggplot
qtpynodeeditor
```
that is why we really should have a migration to move these from `qt=5.12` to `qt-main=5.15` all at once.

**Comment by SrNetoChan** [comment]
Wow, that is a lot... Am some are also needed for QGIS I guess. I am going to look at the documentation provided on that comment. Probably it's way above my head :-)

**Comment by gillins** [comment]
Sorry @izahn i merged this prematurely again. Should we revert this?

**Comment by izahn** [comment]
I think we should push forward with migrating all the other packages rather than reverting this one. QGIS isn't the only one that needs qt 5.15, other packages are stuck on old versions because of this too.

**Pull request merged**
