### PR TITLE
Build with qt-main

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/qtwebkit-feedstock/pull/17

This PR swaps the `qt` dependency for the new `qt-main`. This paves the way for long-blocked updates that depend on more recent qt, including https://github.com/conda-forge/qgis-feedstock/pull/194 and https://github.com/conda-forge/jasp-feedstock/pull/4

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
This one is ready @conda-forge/qtwebkit 

It swaps the `qt` dependency for the new `qt-main`. This paves the way for long-blocked updates that depend on more recent qt, including https://github.com/conda-forge/qgis-feedstock/pull/194 and https://github.com/conda-forge/jasp-feedstock/pull/4

**Comment by gillins** [comment]
Thanks @izahn 

> This paves the way for long-blocked updates that depend on more recent qt

I think we are still blocked on `pyqt` for `qgis`...

**Comment by izahn** [comment]
> Thanks @izahn
> 
> > This paves the way for long-blocked updates that depend on more recent qt
> 
> I think we are still blocked on `pyqt` for `qgis`...

More paving to do...

**Pull request merged**
