### PR TITLE
Try to use qt-main

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
For Linux, it probably needs to set

DQt5_DIR=$your_Qt_path/lib/cmake/Qt5

https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Linux

**Comment by SrNetoChan** [comment]
@gillins any ideas? It seems to be related to the Qt5Gui_PRIVATE_INCLUDE_DIRS. It seem it's not being able to find the 
files in include/qt/QtGui/5.15.2/QtGui/private/

I think {$PREFIX}/include/qt/QtGui/5.15.2/QtGui/private should be added to the Qt5Gui_PRIVATE_INCLUDE_DIRS variable, but I don't know how to do it.

**Comment by gillins** [comment]
Seems to be actually a linking error during the tests:
```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libQt5Core.so.5.15.2: undefined reference to `clock_gettime@GLIBC_2.17'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libQt5Core.so.5.15.2: undefined reference to `getauxval@GLIBC_2.16'
```

Anyone have an idea?

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@ocefpaf any idea of what may be going on in here?

**Comment by gillins** [comment]
@SrNetoChan I was going to wait until `pyqt` attempts this change - I'm sure they'll get a similar error - hopefully might learn something then....

**Comment by SrNetoChan** [comment]
In that case, maybe I will go there and try to trigger things up :-)

**Comment by SrNetoChan** [comment]
Nevermind, we need to wait for webengine work to be completed.

https://github.com/conda-forge/staged-recipes/pull/17233

**Comment by izahn** [comment]
I fixed this up over in https://github.com/conda-forge/qtwebkit-feedstock/pull/18, feel free to copy to this PR, or we can merge mine, whichever you prefer.

**Comment by SrNetoChan** [comment]
> I fixed this up over in https://github.com/conda-forge/qtwebkit-feedstock/pull/18, feel free to copy to this PR, or we can merge mine, whichever you prefer.

Nice!! If you build pass all the checks, let's merge yours and close this one.

**Comment by gillins** [comment]
Thanks @izahn !

@SrNetoChan have you heard if `qgis` going to move away from `qtwebkit` to `qtwebengine`? Seems there isn't a lot of activity upstream on this project anymore...

**Comment by SrNetoChan** [comment]
@gillins if I am not wrong, its more about several "crucial" plugins that are based on qtwebkit. Also, it seems that in qt5 qtwebengine does not completely cover qtwebkit functionality.

I believe the idea would be to give up on qtwebkit when QGIS moves to qt6 where qtwebengine is more complete.

@nyalldawson and others would be able to answer much better than me.

**Comment by nyalldawson** [comment]
@gillins 
> have you heard if qgis going to move away from qtwebkit to qtwebengine? 

There's no plans to, no. Qtwebengine misses crucial functionality which QGIS needs (specifically the ability to render HTML content as vectors to a paint device, so that HTML is exported as vector/text objects in PDF instead of low-resolution rasterised content).


> Seems there isn't a lot of activity upstream on this project anymore...

It moved here: https://github.com/qtwebkit/qtwebkit


> if I am not wrong, its more about several "crucial" plugins that are based on qtwebkit

QGIS itself has core functionality which depends on qtwebkit, not just plugins. If you skip it then you'll miss things like the ability to put HTML blocks in layouts.

**Comment by gillins** [comment]
Thanks @nyalldawson that's good to know. We'll keep maintaining it.

> It moved here: https://github.com/qtwebkit/qtwebkit

Last tag was March 2020, although I see there have been a bunch of commits to `master` more recently. Hopefully they start doing some official releases soon. We are using snapshots taken from https://download.qt.io/snapshots/ci/qtwebkit/5.212/ but that hasn't been updated since September 2020. Where do you build `qtwebkit` from?

**Comment by nyalldawson** [comment]
>Where do you build qtwebkit from?

That's a question for @jef-n, sorry!

**Comment by izahn** [comment]
https://github.com/conda-forge/qtwebkit-feedstock/pull/18 is ready.

**Comment by gillins** [comment]
Closing in favour of #18

**Comment by jef-n** [comment]
> > Where do you build qtwebkit from?

https://github.com/jef-n/OSGeo4W/blob/master/src/qtwebkit/osgeo4w/package.sh

**Comment by gillins** [comment]
Ah ok @jef-n so you use the github tag, maybe we should be doing that also rather than the snapshot from `download.qt.io`... Hopefully there will be a new release soon of `qtwebkit` anyway and we can make sure we are in sync.

**Pull request closed without merging**
