### PR TITLE
revert back to qt

### LINKED ISSUE #20: Revert back to depending on qt instead of qt-main?
Hey folks, I think we may have jumped the gun with https://github.com/conda-forge/qtwebkit-feedstock/pull/18 , now we are blocking https://github.com/conda-forge/qgis-feedstock/pull/226. Should we revert back to depending on `qt` for now?

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/qtwebkit-feedstock/issues/20

### CODE REVIEW

**Comment by izahn** [comment]
`win-64` fails because `mamba` doesn't see the the latest `qt` build for that platform for some reason. I asked about it in https://github.com/conda-forge/qt-feedstock/pull/214#issuecomment-1031568440

**Comment by izahn** [comment]
There were problems with the latest `qt` build for `win_64` as detailed in https://github.com/conda/infra/discussions/514 and https://github.com/conda-forge/qt-feedstock/pull/214#issuecomment-1031568440 so now we are stuck here too until someone can rebuild qt for windows.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
https://github.com/conda/infra/discussions/514 was finally resolved, I think we should merge this in order to allow https://github.com/conda-forge/qgis-feedstock/pull/227 to proceed.

Of course by the time we finally get this sorted out `qt 5.15` will finally be ready and we'll go back again...

**Comment by gillins** [comment]
Thanks @izahn !

**Pull request merged**
