### PR TITLE
Pin against same version of Qt that qtwebkit was created for

### PR DESCRIPTION
**Pull request by gillins**
Suggestion from @ocefpaf. See discussion [here](https://github.com/conda-forge/qtwebkit-feedstock/pull/1).

### CODE REVIEW

**Comment by gillins** [comment]
So the build [timed out](https://travis-ci.org/conda-forge/qtwebkit-feedstock/builds/362873878#L2712). Is 49 minutes our limit on Travis? This would explain why no packages have been built for `qtwebkit`...

Somehow this recipe built in staged-recipes (https://travis-ci.org/conda-forge/staged-recipes/builds/362036529?utm_source=github_status&utm_medium=notification) - needed 51 minutes!

**Comment by ocefpaf** [comment]
I'll write Travis-CI to ask if they can increase the time here.

**Comment by gillins** [comment]
Merging for now...

**Comment by ocefpaf** [comment]
I asked Travis-CI to see if we can get more time for this feedstock. No answer so far :-(

However, @isuruf is working on an alternative that uses CircleCI OS X instances. That may be useful here.

**Comment by isuruf** [comment]
My conda-smithy branch should work. (For using CircleCI osx instances.) Add `osx_provider: circle` to conda-forge.yml and rerender

**Comment by ocefpaf** [comment]
Thanks @isuruf! @gillins is in Australia so I guess I will try it right now before he wakes up :smile:

**Pull request merged**
